### ISSUE TITLE
Running example throws `No module named 'splash_structure_py.src'`

### ISSUE THREAD

**Issue by biona001** [juliefrwang/splash-structure#1]
I tried to follow the installation instructions, which worked, but I seem to get an error when trying to run the example test:
```shell
$ python3 -m venv my_env
$ source my_env/bin/activate
$ git clone https://github.com/juliefrwang/splash-structure.git
$ cd splash-structure
$ pip install .
$ ss-target new_test tests/test_data/test.after_correction.scores.tsv
Traceback (most recent call last):
  File "/Users/biona001/.julia/dev/splash-structure/my_env/bin/ss-target", line 5, in <module>
    from splash_structure_py.structure_target_mode import run_SS_target
  File "/Users/biona001/.julia/dev/splash-structure/my_env/lib/python3.10/site-packages/splash_structure_py/structure_target_mode.py", line 16, in <module>
    from splash_structure_py.src.parse_args import *
ModuleNotFoundError: No module named 'splash_structure_py.src'
```

However, within python, I can import that module
```
$ python
Python 3.10.6 (v3.10.6:9c7b4bd164, Aug  1 2022, 17:13:48) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
>>> from splash_structure_py.src.parse_args import *
>>>
```

**Comment by juliefrwang** [comment]
Thanks for reporting this issue. It's been resolved.
